language: java
# use Java 8
jdk:
  - oraclejdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2

# Code Coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    develop: powerline-backend-staging
    master: powerline-backend-production
