version: '3.5'
services:
  db:
    container_name: creeware-db
    image: postgres:11.2-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/gitlab_data
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/gitlab_data

volumes:
  db-data:
    driver: local
